// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using adet_midterm_q2_jintalan_mikaela.Models;

namespace adetmidtermq2jintalanmikaela.Migrations
{
    [DbContext(typeof(AdetPortalDbContext))]
    [Migration("20201206160052_[adetPortal]")]
    partial class adetPortal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("adet_midterm_q2_jintalan_mikaela.Models.AdetPortal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("FA1")
                        .HasColumnType("float");

                    b.Property<double>("FA2")
                        .HasColumnType("float");

                    b.Property<double>("FA3")
                        .HasColumnType("float");

                    b.Property<double>("FCG")
                        .HasColumnType("float");

                    b.Property<double>("FQ1")
                        .HasColumnType("float");

                    b.Property<double>("FQ2")
                        .HasColumnType("float");

                    b.Property<double>("FQ3")
                        .HasColumnType("float");

                    b.Property<double>("MA1")
                        .HasColumnType("float");

                    b.Property<double>("MA2")
                        .HasColumnType("float");

                    b.Property<double>("MA3")
                        .HasColumnType("float");

                    b.Property<double>("MCG")
                        .HasColumnType("float");

                    b.Property<double>("MQ1")
                        .HasColumnType("float");

                    b.Property<double>("MQ2")
                        .HasColumnType("float");

                    b.Property<double>("MQ3")
                        .HasColumnType("float");

                    b.Property<double>("PA1")
                        .HasColumnType("float");

                    b.Property<double>("PA2")
                        .HasColumnType("float");

                    b.Property<double>("PA3")
                        .HasColumnType("float");

                    b.Property<double>("PCG")
                        .HasColumnType("float");

                    b.Property<double>("PFA1")
                        .HasColumnType("float");

                    b.Property<double>("PFA2")
                        .HasColumnType("float");

                    b.Property<double>("PFA3")
                        .HasColumnType("float");

                    b.Property<double>("PFCG")
                        .HasColumnType("float");

                    b.Property<double>("PFQ1")
                        .HasColumnType("float");

                    b.Property<double>("PFQ2")
                        .HasColumnType("float");

                    b.Property<double>("PFQ3")
                        .HasColumnType("float");

                    b.Property<double>("PQ1")
                        .HasColumnType("float");

                    b.Property<double>("PQ2")
                        .HasColumnType("float");

                    b.Property<double>("PQ3")
                        .HasColumnType("float");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudentPortal");
                });
#pragma warning restore 612, 618
        }
    }
}
